services:
  # PostgreSQL database with PGVector extension for vector similarity search
  postgres:
    image: pgvector/pgvector:pg16
    container_name: docassist-postgres
    environment:
      POSTGRES_DB: docassist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - docassist-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d docassist"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  docassist-network:
    driver: bridge

  